---
title: "Examples using some small helper functions"
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(drcHelper)
```

## Williams' Test

Note that PMCMRplus does not produce correct t-statistics in the version "1.9.12" (mayber also in other versions), therefore we replace the t-statistics using the ones calculated by multcomp. 

```{r}
# Create example data
set.seed(123)
test_data <- data.frame(
  dose = factor(rep(c(0, 1, 5, 10), each = 5)),
  response = c(rnorm(5, 100, 10), rnorm(5, 90, 10),
               rnorm(5, 80, 10), rnorm(5, 70, 10))
)
#'
# Apply Williams test
result <- broom_williams(response ~ dose, data = test_data,method="Williams_PMCMRplus")
print(result)

result <- broom_williams(response ~ dose, data = test_data, method = "Williams_JG")
print(result)
```

## Dunnett's Test


Note that Dunnett's test outcome from different packages are also different. It will depends on what need to be reported to tidy the result table. 

```{r}
# Apply  test
result <- broom_dunnett(response ~ dose, data = test_data,method = "Dunnett_multcomp")
print(result)

result <- broom_dunnett(response ~ dose, data = test_data,method = "Dunnett_DescTools")
print(result)

result <- broom_dunnett(response ~ dose, data = test_data,method = "Dunnett_PMCMRplus")
print(result)
```

