- Build and Check

Clean and Rebuild

```{r}
devtools::clean_dll()
devtools::load_all()
devtools::document()
```


- Build ReadMe GitHub page

```{r}
devtools::build_readme()
```

- Build documentation site

```{r}
pkgdown::build_site_github_pages(clean=FALSE)
```

- Git

```
git push -u origin releases
```

or

```
git push --set-upstream origin <your branch name>
```


Create a new branch and push to origin:

```
git checkout -b <name of branch>

git push -u origin <name of branch>
```

## Tag

```
git tag <tag_name>
git describe
git push origin <tag_name>
```

## Find a string
```
find / -type f -exec grep -H 'text-to-find-here' {} \;
grep -rnw '/path/to/somewhere/' -e 'contEndpoint'

find . -name "*.Rmd" | xargs -d '\n' grep -i "contEndpoint"
# Navigate to your package directory
cd path/to/drcHelper

# Search for "plot.edList" in all R files
grep -r "plot.edList" --include="*.R" .
```

## check and build

### Find non-ASCII characters

```
tools::showNonASCII("~/R/stepdown_binom.R")
```

### Too many imports

Move packages that are only used in:

- Examples
- Vignettes
- Optional functionality
- Specific methods that users might not need

to Suggests. Example:

```
# In DESCRIPTION
Suggests: 
    ggplot2,
    dplyr,
    knitr,
    rmarkdown,
    testthat

# Then use conditionally in code
if (requireNamespace("ggplot2", quietly = TRUE)) {
    # ggplot2 code here
} else {
    stop("Package 'ggplot2' is required for this function. Please install it.")
}


# Internal helper that checks for package availability
check_package <- function(pkg) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
        stop(sprintf("Package '%s' is required but not installed.", pkg),
             call. = FALSE)
    }
}

# Use in functions
my_function <- function(...) {
    check_package("dplyr")
    # dplyr code here
}
```

