---
title: "Quarto Basics"
format: docx
---

## DescTools

- Focus:

```r
DescTools::DunnettTest
DescTools::JonckheereTerpstraTest
DescTools::CochranArmitageTest
```

-  Nice to have

```r
DescTools::Desc
```

## drcHelper

In general, the testing included in the package already covers most of the functions that will be used in GLP calculation.

### Functions needs testing and not covered fully by the unit testing

1. R/drc_Helper.R
    - addECxCI
    - getModelName
    - plot.modList
    - plot_edList
    - mselect.ED
    - calcNW

2. R/preliminary.R
    - prelimPlot3
    
3. R/quantal.R
    - many_to_one_fisher_test
    
4. 

### Not covered by testing but not needed in GLP env

all function in R/dunnett.R, R/broom.R, R/williams_JT.R.

Functions in R/dose_response_simulation.R are nice to have but these are for simulations and not for calculations.

Functions in R/brsr_tsk.R


### Functions I don't think testing is necessary

in R/zzz.R, I defined some onload actions to avoid S3 method warning when checking the package, I don't think they need validation



