---
title: "Simulation Based Power Analysis"
description: | 
  Collection of Notes on MM
date: December 4, 2024
author:
  - first_name: "Zhenglei"
    last_name: "Gao"
    url: https://github.com/Zhenglei-BCS
    affiliation: Bayer AG
    affiliation_url: https://bayer.com
    orcid_id: 0000-0002-4042-310X
editor_options: 
  chunk_output_type: console
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
library(tidyverse)
```

```{r}
library(drcHelper)
```



```{r eval=FALSE}
## Note: to generate this plot, need to source the definition of response_patterns and  plot_variance_patterns
p1 <- response_patterns
p2 <- plot_variance_patterns(5,4,c(0,20))
p1 <- p1+theme(legend.position = "bottom")+guides(color=guide_legend(nrow=2,byrow=TRUE))
p2 <- p2 + ggplot2::scale_color_viridis_d(direction = 1)+theme(legend.position = "bottom")+guides(color=guide_legend(nrow=2,byrow=TRUE))
library(patchwork)
p1+p2
p1+p2 & plot_annotation(tag_levels = 'A')
ggsave("Figure_1_respnse_variance_pattern.png",dpi = 300,width = 7.5,height = 4)
```


## Outcome Discussion





## References

- The Abuse of Power: https://www.tandfonline.com/doi/abs/10.1198/000313001300339897#preview
- SIMR: power analysis for GLMM https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12504
