---
title: "System Testing"
description: | 
  Testing approaches and description of test cases
date: December 4, 2024
author: "Zhenglei Gao"
---


## Purpose of Testing

The testing in this phase is to ensure the R package and the UI on top of it meet all user requirements (URS) and behaves as the end users expect. If any of the tests fail, it is possible to detect loopholes and fix errors early in development. 

Note that access security and scalability are taken care of by the V-COP environment. The purpose of this testing is limited to all functional requirements. Interfacing ability via API with V-COP file management and  the validated run environment is designed to be tested manually. 

One important aspect of testing is to verify the functions used in the analysis do what they are supposed to do. There are many functions in different R packages designed to perform the same task, however, with different assumptions behind. The outcome may be similar or different, it is important that we understand the details and choose the most appropriate ones. 


## Structure of Testing

### Unit Testing for this Helper Package

### Unit Testing for Other R functions involved in the Analysis


### System Testing
